keys:
  # ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ37RZ3TIIuDNS3wcaQ4t0z5NkT1H4GukVcke3GNOn40 krishnans2006@gmail.com
  - &krishnan-lap age1eeafyyhzw59fhrnd8v87lrk4yvsu42uk4glmgpzdy7k59huzpquq0zvjz7
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *krishnan-lap
