# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-65f2a93e-b43f-4499-9e6f-d649b0f04fde";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-65f2a93e-b43f-4499-9e6f-d649b0f04fde".device = "/dev/disk/by-uuid/65f2a93e-b43f-4499-9e6f-d649b0f04fde";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/46CC-F806";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3a234895-6078-46cb-84d9-1209a33e4cfa"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
